#!/bin/sh -e

apk upgrade --no-cache --no-progress
apk add --no-cache --no-progress \
    alsa-lib-dev \
    bzip2-dev \
    curl-dev \
    file-dev \
    freeglut-dev \
    glfw-dev \
    icu-dev \
    libgit2-dev \
    libsndfile-dev \
    libxcursor-dev \
    libxft-dev \
    libxml2-dev \
    libxrandr-dev \
    libzip-dev \
    lmdb-dev \
    nettle-dev \
    pcre-dev \
    postgresql-dev \
    sdl2_image-dev \
    sdl2_mixer-dev \
    sdl2_ttf-dev \
    xz-dev \
    zeromq-dev

stack --no-terminal --resolver nightly-2017-12-01 install --haddock \
    accelerate-llvm-native \
    Agda \
    alarmclock \
    alex \
    apecs \
    apply-refact \
    arithmoi \
    atom-conduit \
    backprop \
    bench \
    bindings-GLFW \
    bitcoin-api-extra \
    bound \
    brittany \
    c2hs \
    cabal-install \
    cabal-rpm \
    cabal-toolkit \
    cassava \
    cast \
    Chart-diagrams \
    chart-unit \
    classy-prelude-yesod \
    compact \
    compensated \
    cpphs \
    curl \
    dhall \
    dhall-bash \
    dhall-json \
    dhall-nix \
    dhall-text \
    diagrams \
    diagrams-canvas \
    dice \
    dimensional \
    direct-rocksdb \
    distributed-closure \
    distributed-process-simplelocalnet \
    distributed-process-tests \
    djinn-ghc \
    docker-build-cacher \
    doctest \
    effect-handlers \
    ekg \
    emailaddress \
    errors-ext \
    ersatz \
    esqueleto \
    ether \
    eventstore \
    extensible-effects \
    extrapolate \
    fast-builder \
    feed \
    fixed-vector-hetero \
    free-vl \
    generic-lens \
    ghc-events \
    ghcid \
    git \
    git-annex \
    github \
    github-webhook-handler-snap \
    github-release \
    gloss \
    gnuplot \
    GPipe \
    hapistrano \
    happy \
    haskell-tools-cli \
    haskell-tools-debug \
    haskell-tools-demo \
    haxl \
    hedgehog-quickcheck \
    hindent \
    hint \
    hip \
    hit \
    hjsonschema \
    hlint \
    hoogle \
    hopenpgp-tools \
    hpack \
    hpp \
    hprotoc \
    hscolour \
    hsexif \
    hsndfile-vector \
    hspec-checkers \
    hspec-discover \
    hworker \
    hyperloglog \
    influxdb \
    inline-c-cpp \
    integration \
    intero \
    irc-client \
    ixset \
    json-autotype \
    json-stream \
    katip-elasticsearch \
    katydid \
    language-java \
    large-hashable \
    LibZip \
    lmdb \
    log-domain \
    log-elasticsearch \
    log-warper \
    machines-binary \
    machines-directory \
    machines-io \
    megaparsec \
    messagepack-rpc \
    midi-music-box \
    milena \
    minio-hs \
    misfortune \
    mmark-ext \
    morte \
    netwire-input \
    network-anonymous-i2p \
    network-anonymous-tor \
    network-msgpack-rpc \
    network-transport-composed \
    network-transport-inmemory \
    network-transport-tests \
    NoTrace \
    opaleye-trans \
    open-browser \
    operational \
    pandoc \
    pandoc-citeproc \
    pcre-heavy \
    pdf-toolbox-document \
    perf \
    pretty-show \
    protobuf-simple \
    protocol-buffers-descriptor \
    proto-lens-arbitrary \
    proto-lens-combinators \
    proto-lens-optparse \
    proto-lens-protobuf-types \
    quickbench \
    raaz \
    rainbox \
    random-fu \
    reactive-banana \
    repa-algorithms \
    repa-io \
    repline \
    SafeSemaphore \
    sbv \
    scalpel \
    schematic \
    sdl2-image \
    sdl2-mixer \
    sdl2-ttf \
    selda-postgresql \
    selda-sqlite \
    servant-client \
    servant-swagger-ui \
    servant-websockets \
    shake \
    shake-language-c \
    ShellCheck \
    soap-openssl \
    squeal-postgresql \
    stm-containers \
    stm-supply \
    stylish-haskell \
    swish \
    syb-with-class \
    tardis \
    tasty-quickcheck \
    tasty-smallcheck \
    TCache \
    text-icu \
    threepenny-editors \
    threepenny-gui-flexbox \
    transient-universe \
    tree-diff \
    true-name \
    twitter-conduit \
    type-combinators-singletons \
    unagi-chan \
    unbound-generics \
    unboxed-ref \
    unification-fd \
    union \
    Unique \
    userid \
    users-persistent \
    users-postgresql-simple \
    users-test \
    utf8-light \
    vcswrapper \
    viewprof \
    wai-app-static \
    wai-middleware-rollbar \
    wai-session-postgresql \
    wai-websockets \
    wavefront \
    webdriver \
    websockets-rpc \
    weigh \
    wreq \
    yaml \
    Yampa \
    xeno \
    xmonad \
    xmonad-extras \
    zeromq4-haskell \
    zim-parser \
    zippers \
    zm \
    ztail

rm /tmp/bootstrap.sh
