GhcEnableTablesNextToCode = NO
INTEGER_LIBRARY           = integer-simple
StripLibraries            = YES
SRC_HC_OPTS               = -O -H256m
GhcStage1HcOpts           = -O
GhcStage2HcOpts           = -O2
GhcLibHcOpts              = -O2
BUILD_PROF_LIBS           = NO
SplitSections             = YES
BUILD_SPHINX_HTML         = YES
BUILD_SPHINX_PDF          = NO
BUILD_MAN                 = NO
HADDOCK_DOCS              = YES
EXTRA_HADDOCK_OPTS        += --quickjump --hyperlinked-source
