version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u terrorjack -p $DOCKER_PASS
          docker build -t terrorjack/meikyu:ghc-8.3.20171111 .
          docker push terrorjack/meikyu:ghc-8.3.20171111
