version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      - GHC_LIB_VER: "8.5"
      - GHC_REV: 5695f462f604fc63cbb45a7f3073bc114f9b475f
      - GHC_VER: "8.5.20171208"
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker login -u terrorjack -p $DOCKER_PASS
          docker build --build-arg GHC_LIB_VER=$GHC_LIB_VER --build-arg GHC_REV=$GHC_REV --build-arg GHC_VER=$GHC_VER --build-arg GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN -t terrorjack/meikyu:ghc-$GHC_VER -t terrorjack/meikyu:ghc-head .
          docker push terrorjack/meikyu:ghc-$GHC_VER
          docker push terrorjack/meikyu:ghc-head
